algoritmo "estrutura de repetição"
// Função :
// Autor :  Giovanna Cavalcante
// Data : 28/07/2021
// Seção de Declarações
var
n: inteiro

inicio
// Seção de Comandos
escreva ("Declare um número:")
leia (n)
enquanto (n <> 0) faca
   se (n mod 2= 0) entao
      escreva ("Esse número é PAR")
   senao
      escreva ("Esse número é ÍMPAR")
   fimse
   escreva (" Informe um número:")
   leia (n)
   fimenquanto
   escreva ("Digite 0 para finalizar")

fimalgoritmo
