algoritmo "semnome"
// Função :
// Autor :
// Data : 31/07/2021
// Seção de Declarações
var
 idades: vetor[1..7] de inteiro
 nomes: vetor [1..7] de caractere
i:inteiro




inicio
// Seção de Comandos

 para i de 1 ate 7 faca
 escreva ("Informe nome e idade do aluno:")
 leia (nomes[i])
 leia (idades[i])
 fimpara
 escreva ("Dados do 5º aluno:" , nomes[5], idades[5])

fimalgoritmo
