algoritmo "semnome"
// Função :
// Autor :
// Data : 03/08/2021
// Seção de Declarações
var
nome: vetor [1..2] de caractere
idade : vetor [1..2] de inteiro
inicio
// Seção de Comandos
escreval ("Informe um nome:")
leia (nome[1])
escreval ("Informe sua idade:")
leia (idade[1])
nome [2]<- "Paulo"
idade [2] <- 23
escreva (" Nome informado foi" , nome [1] ,"idade informada foi" ,idade [1] )


fimalgoritmo
